name: feed_dac_module
description: The implementation and web wrapper for the Feed DAC
version: 0.1.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  canonical_json: ^1.1.1
  convert: ^3.0.1
  crypto: ^3.0.2
  skynet:
    path: ../../skynet
  skynet_dacs_library:
    path: ../library-dart
  dac_modules_base:
    path: ../dac-modules-base
  social_dac_module:
    path: ../social-dac
  bridge_dac_module:
    path: ../bridge-dac
  messagepack:
    git: https://github.com/ldoney/messagepack.git
  hive: ^2.1.0
  tuple: ^2.0.0
  async: ^2.8.0
  pool: ^1.5.0

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^1.0.0
